### ISSUE TITLE
PyQt5 required?

### ISSUE THREAD

**Issue by vigji** [brainglobe/bgviewer#2]
I tried to install in new env and I had to manually install pyqt5, so maybe the specification in the requirements is not working? I never used this `package[anotherpackage]` syntax, maybe I am doing something wrong. Installing with `pip install -e `.

**Comment by adamltyson** [comment]
This is weird, did you have anything installed in the env?

This syntax appears to be working ok for cellfinder and amap.

**Comment by vigji** [comment]
Actually yes, I tried in a fresh environment and now it seems to be fine.

**Comment by FedeClaudi** [comment]
I had something similar happen, maybe it happens if you have napari already installed in your environment (without `[pyqt]`)?

This is probably the cause:
![image](https://user-images.githubusercontent.com/17436313/84925912-86cdce00-b0c2-11ea-8b06-9c2631294867.png)

----
We should maybe catch this with an appropriate message as it's bound to happen to others

**Comment by adamltyson** [comment]
Oh yeah, if you already have napari, it won't install pyqt5. You may have already had pyside2 installed instead. Maybe we should just revert, and require pyqt5?

**Comment by FedeClaudi** [comment]
done
